version: 0.2
run-as: root

env:
  variables:
    key: "value"
    key: "value"
  parameter-store:
    key: "value"
    key: "value"
            
phases:
  pre_build:
    run-as: root
    commands:
      - npm install
    finally:
      - npm run bootstrap
  build:
    run-as: root
    commands:
      - npm run up
artifacts:
  files:
    - '*.*'
  discard-paths: no
  base-directory: .
cache:
  paths:
    - node_modules
    - bin