version: 0.2
run-as: root

env:
  variables:
    TERM: "xterm"
            
phases:
  install: 
    run-as: root
    commands: 
      - npm install
  # pre_build:
  #   run-as: root
  #   commands:
  #     - npm run bootstrap
  build:
    run-as: root
    commands:
      - npm run up
artifacts:
  files:
    - '*.*'
  discard-paths: no
  base-directory: .
cache:
  paths:
    - node_modules
    - bin